kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    k8s-app: httpd
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: httpd
  template:
    metadata:
      labels:
        k8s-app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd