apiVersion: v1
kind: Pod
metadata:
  name: storage
  namespace: default
  labels:
    env: test
spec:
  containers:
  - name: storage
    image: ikubernetes/myapp:v1
    volumeMounts:
    - name: myvolumes
      mountPath: /app/log/config.d/
      readOnly: true
    ports:
    - containerPort: 80
  volumes:
  - name: myvolumes
    configMap:
      name: myconfig