apiVersion: v1
kind: Pod
metadata:
  name: storage
  namespace: default
  labels:
    env: test
spec:
  containers:
  - name: storage
    image: ikubernetes/myapp:v1
    volumeMounts:
    - name: log
      mountPath: /app/log/
    ports:
    - containerPort: 80
  volumes:
  - name: log
    hostPath:
      path: /app/log/
      type: DirectoryOrCreate