apiVersion: v1
kind: Pod
metadata:
  name: mysa
  namespace: default
  labels:
    env: test
spec:
  serviceAccountName: mysa
  containers:
  - name: mysa
    image: ikubernetes/myapp:v1
    volumeMounts:
    - name: log
      mountPath: /app/log/
    ports:
    - containerPort: 80
  volumes:
  - name: log
    hostPath:
      path: /app/log/
      type: DirectoryOrCreate