apiVersion: v1
kind: Service
metadata:
  name: myservices
  namespace: default
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: htp
    port: 80
    targetPort: 80
    nodePort: 30009