apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: v1.12.1
networking:
  podSubnet: "10.244.0.0/16"
apiServerCertSANs:
- "ip"
etcd:
  external:
    endpoints:
    - http://etcd1:2379
    - http://etcd2:2379
    - http://etcd3:2379